version: "3.8"

services:
  postgres_db:
    image: postgres:16
    container_name: academy_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/var/lib/redis/data/

  web:
    build: .
    container_name: bank_backend
    # volumes:
    #   - ./:/usr/src/app/
    command: [ "/usr/src/app/docker/app.sh" ]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/usr/src/app/docker/celery.sh", "celery" ]
    env_file:
      - .env
    container_name: celery_app
    depends_on:
      - web
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/usr/src/app/docker/celery.sh", "flower" ]
    env_file:
      - .env
    container_name: flower_app
    depends_on:
      - web
      - redis
      - celery
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  redis_cache: