"""empty message

Revision ID: c586eff244cb
Revises: 55f4a140f28f
Create Date: 2024-03-24 17:06:15.736048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c586eff244cb'
down_revision: Union[str, None] = '55f4a140f28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'is_approved')
    # ### end Alembic commands ###
