"""empty message

Revision ID: edd3cf3541f4
Revises: fe08569f402b
Create Date: 2024-03-17 00:00:13.204178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd3cf3541f4'
down_revision: Union[str, None] = 'fe08569f402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_bank_combination', 'bank_user_association', ['user_id', 'bank_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_bank_combination', 'bank_user_association', type_='unique')
    # ### end Alembic commands ###
