"""empty message

Revision ID: 4d3f1ba771aa
Revises: 0b8e7c2156e9
Create Date: 2024-03-19 00:28:58.285591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3f1ba771aa'
down_revision: Union[str, None] = '0b8e7c2156e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('amount_expected', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'amount_expected')
    # ### end Alembic commands ###
