"""empty message

Revision ID: 0b8e7c2156e9
Revises: 4ac29c88cc41
Create Date: 2024-03-19 00:05:58.055313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8e7c2156e9'
down_revision: Union[str, None] = '4ac29c88cc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('is_covered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'is_covered')
    # ### end Alembic commands ###
