"""empty message

Revision ID: 150d9cd44e84
Revises: 5d315cfefcf4
Create Date: 2024-03-19 01:25:21.419626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150d9cd44e84'
down_revision: Union[str, None] = '5d315cfefcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loan_user_id_fkey', 'loan', type_='foreignkey')
    op.drop_column('loan', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('loan_user_id_fkey', 'loan', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
