"""empty message

Revision ID: fcab345eb05a
Revises: a35c397da33d
Create Date: 2024-03-21 22:53:35.885990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcab345eb05a'
down_revision: Union[str, None] = 'a35c397da33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_account_in_bank', 'account', ['user_id', 'bank_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_account_in_bank', 'account', type_='unique')
    # ### end Alembic commands ###
