"""empty message

Revision ID: 2fc6280364c9
Revises: cce61071f8f9
Create Date: 2024-03-18 22:55:53.973474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc6280364c9'
down_revision: Union[str, None] = 'cce61071f8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('loan_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('loan_loan_type_fkey', 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'loan_type', ['loan_type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('loan', 'loan_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('loan_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key('loan_loan_type_fkey', 'loan', 'loan_type', ['loan_type'], ['id'], ondelete='RESTRICT')
    op.drop_column('loan', 'loan_type_id')
    # ### end Alembic commands ###
